%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /home/vitor/Programas/FP/input/DLIN.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/09/29 15:39:45

%% Import the data
[~, ~, raw] = xlsread('/home/vitor/Programas/FP/input/DLIN.xlsx','Sheet1');
raw = raw(2:end,:);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
DLIN = table;

%% Allocate imported array to column variable names
DLIN.lin = data(:,1);
DLIN.From = data(:,2);
DLIN.To = data(:,3);
DLIN.r = data(:,4);
DLIN.x = data(:,5);
DLIN.bsh = data(:,6);

%% Clear temporary variables
clearvars data raw;