%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /home/vitor/Programas/FP/input/DBAR.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/09/29 15:33:54

%% Import the data
[~, ~, raw] = xlsread('input/DBAR.xlsx','Sheet1');
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
DBAR = table;

%% Allocate imported array to column variable names
DBAR.bus = data(:,1);
DBAR.type = data(:,2);
DBAR.sh = data(:,3);
DBAR.Pesp = data(:,4);
DBAR.Qesp = data(:,5);
DBAR.V = data(:,6);
DBAR.teta = data(:,7);

%% Clear temporary variables
clearvars data raw R;